development:
  address: 'smtp.mandrillapp.com'
  port:  587
  enable_starttls_auto: true
  domain: 'nuctecs.com'
  user_name: 'gabe@nuctecs.com'
  password: 'ZNBSmqZbJLUrrDAj5knVKg'
  authentication: login
  domain: nuctecs.com

test:
  address: 'smtp.mandrillapp.com'
  port:  587
  enable_starttls_auto: true
  domain: 'nuctecs.com'
  user_name: 'gabe@nuctecs.com'
  password: 'ZNBSmqZbJLUrrDAj5knVKg'
  authentication: login
  domain: nuctecs.com

production:
  address: 'smtp.mandrillapp.com'
  port:  587
  enable_starttls_auto: true
  domain: 'nuctecs.com'
  user_name: 'gabe@nuctecs.com'
  password: 'ZNBSmqZbJLUrrDAj5knVKg'
  authentication: login
  domain: nuctecs.com
