development:
  address: 'smtp.mandrillapp.com'
  port:  587
  enable_starttls_auto: true
  domain: 'coursecoda.com'
  user_name: 'gabe@coursecoda.com'
  password: 'ZNBSmqZbJLUrrDAj5knVKg'
  authentication: login
  domain: coursecoda.com

test:
  address: 'smtp.mandrillapp.com'
  port:  587
  enable_starttls_auto: true
  domain: 'coursecoda.com'
  user_name: 'gabe@coursecoda.com'
  password: 'ZNBSmqZbJLUrrDAj5knVKg'
  authentication: login
  domain: coursecoda.com

production:
  address: 'smtp.mandrillapp.com'
  port:  587
  enable_starttls_auto: true
  domain: 'coursecoda.com'
  user_name: 'gabe@coursecoda.com'
  password: 'ZNBSmqZbJLUrrDAj5knVKg'
  authentication: login
  domain: coursecoda.com
